### ISSUE TITLE
Which battery value is supposed to be correct?

### ISSUE THREAD

**Issue by ariccio** [Anrijs/Aranet4-Python#12]
This is weird. I'm seeing right now the battery service (`0000180f-0000-1000-8000-00805f9b34fb`, `00002a19-0000-1000-8000-00805f9b34fb`) return a correct value (11%), but the CO2 measurement characteristic (`f0cd1503-95da-4f4b-9ac8-aa55d312af0c`) is returning an entirely different value (45%).

Any idea what's going on? Not really an issue with your repo here, but might be useful to someone :)

**Comment by Anrijs** [comment]
Just checked both battery values on 2 devices. Both characteristics returned same values. Are you sure you checked correct byte for battery value?
I have been using value from `f0cd1503-95da-4f4b-9ac8-aa55d312af0c` without problems. Graphs seems fine.

**Comment by ariccio** [comment]
You know what? I think you may be right? The way it's done in javascript is mildly confusing. I may need to write my own constant offset table so I don't mess it up again. Do I have this field right, here?:

0: SS:SS: CO2
2: TT:TT: Temperature
4: UU:UU: Pressure
6: VV: Humidity
7: WW: Battery?
8: XX: status color?

**Comment by Anrijs** [comment]
Yes, this should be correct. 8th byte is battery.
