### ISSUE TITLE
Changing settings ("writes")

### ISSUE THREAD

**Issue by purpleidea** [Anrijs/Aranet4-Python#20]
With the app you can change some settings, in particular the interval at which the sensor takes readings. The default is 5 or 10 min, but it might be nice to be able to change it to 1min by API.

If someone has reversed this, that would be especially cool. I could help implement the golang variants, if someone has done the python ones.

As an aside, it would be awesome to see some custom firmware for this kind of device. It can't be too complicated, and then we would have more freedom on what we could do to them.

Cheers!

**Comment by Anrijs** [comment]
Changing interval, Bluetooth range and home integrations toggle will be available in upcoming release.
```
$ aranetctl --help

[...]

Change device settings:
  --set-interval MINUTES
                        Change update interval
  --set-integrations {on,off}
                        Toggle Smart Home Integrations
  --set-range {normal,extended}
                        Change bluetooth range
```

**Comment by purpleidea** [comment]
That's awesome, nice work!
