### ISSUE TITLE
history data retrieval fails

### ISSUE THREAD

**Issue by rezgalis** [Anrijs/Aranet4-Python#4]
Apologies for not creating a proper pull request and making notes here:

-l parameter does not work, because two additional libraries have to be imported:
```
import time, datetime
```

Then, in python script lines 114, 117, 120 an 123 need an update - instead of "Aranet4" (e.g. Aranet4.PARAM_CO2) we need to use ar4 (e.g. ar4.PARAM_CO2)

Many thanks for your work, much appreciated and really nice thing to have!

**Comment by Anrijs** [comment]
Fixed. Forgot to move imports to main file, after commit f37c585b00df8016f9d85b9d5e267aad10bdcdbc
