### ISSUE TITLE
Aranet Radon Support

### ISSUE THREAD

**Issue by starsoccer** [Anrijs/Aranet4-Python#44]
Recently a new sensor has been released for radon. It would be great to add support for it, https://aranet.com/products/aranet-radon-sensor

Happy to help however I can.

**Comment by Anrijs** [comment]
It's not released yet. I will add support as soon as I can get it.

**Comment by starsoccer** [comment]
Oh okay, I just got mine in the mail so figured others did as well. No rush, but happy to test or help however I can to get it added.

**Comment by Anrijs** [comment]
Check out v2.4.0b1. It should now support radon sensor.
`pip install aranet4==2.4.0b1`

**Comment by starsoccer** [comment]
Just to confirm do I just use the advanced ssh/terminal and run that command? And then see if it picks up my device on bluetooth?

**Comment by Anrijs** [comment]
Yes, run this it in terminal and it should show up in `aranetctl --scan` command output

**Comment by starsoccer** [comment]
Well the scan command found it:
```
=======================================
  Name:     AranetRn+ XXXXX
  Address:  XXXXXXXXXXXXXXXX
  RSSI:     -79 dBm
---------------------------------------
  Radon Conc.:    23 Bq/m3
  Temperature:    24.7 °C
  Humidity:       51.1 %
  Pressure:       1012.6 hPa
  Battery:        100 %
  Age:            47/600
```

AAny way to force the integration to pick it up or do I need to wait for a HA update for that?

**Comment by Anrijs** [comment]
Home assistant will also require code update. I will try to work on it in upcoming days

**Comment by starsoccer** [comment]
Okay sounds good, happy to help test anything you need

**Comment by Anrijs** [comment]
Home Assistant [2024.9.0](https://rc.home-assistant.io/changelogs/core-2024.9) should now support it.

**Comment by starsoccer** [comment]
Confirmed it working now
