### ISSUE TITLE
V2 Device Does Not Respect "start"

### ISSUE THREAD

**Issue by harrison-caudill** [Anrijs/Aranet4-Python#53]
My Aranet4 does not seem to respect the command packed up here:
https://github.com/Anrijs/Aranet4-Python/blob/master/aranet4/client.py#L808

When this is called, it disregards the start value, and returns the entire dataset since pairing.

Have you seen this issue before?

I don't see any obvious documentation on Aranet's website regarding the protocol.  It looks like line 808 was committed 2 years ago by @elyscape and this device is less than 1 year old -- has there maybe been a protocol change?

Please accept my apologies if I'm missing something obvious here.

Thanks,
Harrison

**Comment by Anrijs** [comment]
How are you using it? `get_records` will always return array with max size, but only values in start:end range will be filled. Skipped values will be with value -1.

**Comment by harrison-caudill** [comment]
Yup, that was it.  Didn't think to consider that behavior.  Closing, sorry about the spam.
