### ISSUE TITLE
Integrate sensor in home assistant

### ISSUE THREAD

**Issue by atallo** [Anrijs/Aranet4-Python#7]
Integrate sensor Aranet4 in home assistant.

https://www.home-assistant.io/integrations/

Thanks,

**Comment by KC-inDomus** [comment]
+1

**Comment by ankostis** [comment]
Aranet4 is the prototypical portable Bluetooth CO2-sensor, with excellent battery life (due to e-ink), implicitly suggested by many #COVID19-airborn specialists on aerosols.
It really worths an own intergation, maybe HACS?
