### ISSUE TITLE
Client hangs when used on RaspberryPi

### ISSUE THREAD

**Issue by Armonkee** [Anrijs/Aranet4-Python#8]
the aranet.py program hangs when started on my raspberrypi (version 3, with Stretch)
_ar4.getName()_ and _ar4.getVersion()_ return the name and version ( v0.3.9)
but _ar4.currentReadings(False)_  does not return from _bytearray(c[0].read())_ in client.py

**Comment by Anrijs** [comment]
I have updated readme. Try to repeat pairing process again.
To delete previous pairing data, enter `remove <DEVICE_ADDRESS>` in bluetoothctl

**Comment by Armonkee** [comment]
after following the revised bluetooth installation , the result when running aranet.py:
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
with Python3.5 same issue

**Comment by Anrijs** [comment]
You can try rebooting RPi. If it still doesn't connect after reboot, issue is most likely in RPi bluetooth stack.
I have tested this only on Raspberry Pi 3 Model B, running Raspbian 10 (buster)

**Comment by Anrijs** [comment]
Closed due inactivity
